run:
  skip-dirs:
    - design
    - docs
linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - gofumpt # https://github.com/mvdan/gofumpt#gofumpt -> gofumpt -l -w .
    - goheader
    - goimports
    - revive
    #- gomoddirectives It complains with docker import fix
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    # - cyclop Would be nice to enable this
    # - wrapcheck Helpful to add error tracing
    # - varnamelen Handy to enforce much better readability
    # - wsl would be nice to turn this on
    # - forcetypeassert Usually good to enable
    # - gocritic  Would be nice to enabled this in the future
    # - gochecknoglobals Should enable this at some stage too
    # - godot
    # - godox
    # - goerr113
    # - testpackage
    # - thelper
    # - nlreturn
    # - paralleltest
    # - interfacer
    # - ireturn
    # - lll
    # - gomnd
    # - exhaustivestruct
    # - forbidigo
    # - funlen
    # - gci
