# This compose parallelizes the builds of images for deployments

version: '3.9'
services:
  host:
    image: "testnetobscuronet.azurecr.io/obscuronet/host:latest"
    build:
      context: ../../
      dockerfile: ../../dockerfiles/host.Dockerfile
  contractdeployer:
    image: "testnetobscuronet.azurecr.io/obscuronet/contractdeployer:latest"
    build:
      context: ../../
      dockerfile: ../../testnet/contractdeployer.Dockerfile
  enclave:
    image: "testnetobscuronet.azurecr.io/obscuronet/enclave:latest"
    build:
      context: ../../
      dockerfile: ../../dockerfiles/enclave.Dockerfile