host:
   debug:
      enableDebugNamespace: true
   log:
     level: 1
     path: ""
enclave:
   debug:
      enableDebugNamespace: true
   log:
     level: 1
     path: ""
sequencer:
   systemContractsUpgrader: 0x5