# The node-launcher environment is

network:
   GenesisJSON: "{}"
   gas:
      minGasPrice: +1
   sequencer:
      p2pAddress: sequencer-host:15000
host:
   debug:
        enableDebugNamespace: true
   l1:
      wsURL: ws://eth2network:9000
   log:
      level: 4
enclave:
   db:
      useInMemory: false
   debug:
      enableDebugNamespace: true
   log:
        level: 4
sequencer:
   systemContractsUpgrader: 0xDEe530E22045939e6f6a0A593F829e35A140D3F1