# This compose builds the essential components for running a local testnet

version: '3.9'
services:
  gethnetwork:
    image: "testnetobscuronet.azurecr.io/obscuronet/gethnetwork:latest"
    build:
      context: $ROOT_PATH
      dockerfile: ./testnet/gethnetwork.Dockerfile
  host:
    image: "testnetobscuronet.azurecr.io/obscuronet/host:latest"
    build:
      context: $ROOT_PATH
      dockerfile: ./dockerfiles/host.Dockerfile
  contractdeployer:
    image: "testnetobscuronet.azurecr.io/obscuronet/contractdeployer:latest"
    build:
      context: $ROOT_PATH
      dockerfile: ./testnet/contractdeployer.Dockerfile
  enclave:
    image: "testnetobscuronet.azurecr.io/obscuronet/enclave:latest"
    build:
      context: $ROOT_PATH
      dockerfile: ./dockerfiles/enclave.Dockerfile
  enclave-debug:
    image: "testnetobscuronet.azurecr.io/obscuronet/enclave_debug:latest"
    build:
      context: $ROOT_PATH
      dockerfile: ./dockerfiles/enclave.debug.Dockerfile
  obscuro-scan:
    image: "testnetobscuronet.azurecr.io/obscuronet/obscuroscan:latest"
    build:
      context: $ROOT_PATH
      dockerfile: ./testnet/obscuroscan.Dockerfile
  wallet-extension:
    image: "testnetobscuronet.azurecr.io/obscuronet/walletextension:latest"
    build:
      context: $ROOT_PATH
      dockerfile: ./testnet/walletextension.Dockerfile
  hardhat-deployer:
    image: "testnetobscuronet.azurecr.io/obscuronet/hardhatdeployer:latest"
    build:
      context: $ROOT_PATH
      dockerfile: ./testnet/hardhatdeployer.Dockerfile
