name: Build PR
# Builds and runs tests on each push to a branch PR'ed against main.

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'design/**'
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run:  docker build -t obscuro_enclave -f dockerfiles/enclave.Dockerfile .

      # Makes sure the artifacts are built correctly
      - name: Build
        run: go build -v ./...

      - name: Test
        uses: nick-fields/retry@v2 # Used to automatically perform two retries if the tests fail.
        env:
          USE_GETH_BINARY: true
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 600 # This is a required field. We set it high enough to not be hit in practice.
          command: go test --failfast -v ./...

      - name: Store simulation logs
        uses: actions/upload-artifact@v3
        with:
          name: sim-logs
          path: |
            integration/.build/simulations/sim-log-*.txt
            integration/.build/noderunner/noderunner-*.txt
            integration/.build/wallet_extension/wal-ext-*.txt
        if: always() # Ensures the artifacts are created even if the tests fail.
