name: Build PR
# Builds and runs tests on each push to a branch PR'ed against main.

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'design/**'
      - 'planning/**'
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4

      # Makes sure the artifacts are built correctly
      - name: Build
        run: go build -v ./...

      # Makes sure the binaries for the eth2network are avail for all other tests
      - name: Download eth2network binaries
        run: go test ./... -v -count=1 -run TestEnsureBinariesAreAvail

      - name: Test
        run: go test --failfast -v ./... -count=1

      - name: Store simulation logs
        uses: actions/upload-artifact@v3
        with:
          name: ci-logs
          path: |
            integration/.build/simulations/sim-log-*.txt
            integration/.build/noderunner/noderunner-*.txt
            integration/.build/wallet_extension/wal-ext-*.txt
            integration/.build/eth2/*
        if: always() # Ensures the artifacts are created even if the tests fail.
        retention-days: 2
