# Deploys Obscuroscan on Azure for Dev-testnet
# Builds the Obscuroscan network image, pushes the image to dockerhub and starts the Obscuroscan on azure
#
# Obscuroscan is a docker container that runs the obscuroscan package
# It exposes the following ports:
# HTTP:       80,
#
# Exposes the following addresses: (only accessible internally)
#  dev-testnet-obscuroscan.uksouth.azurecontainer.io

name: '[M] Deploy Dev-Testnet Obscuroscan'

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: testnetobscuronet.azurecr.io
          username: testnetobscuronet
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          DOCKER_BUILDKIT=1 docker build -t testnetobscuronet.azurecr.io/obscuronet/dev_testnet_obscuroscan:latest -f testnet/obscuroscan.Dockerfile  .
          docker push testnetobscuronet.azurecr.io/obscuronet/dev_testnet_obscuroscan:latest

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: dev-testnet-obscuroscan
          image: testnetobscuronet.azurecr.io/obscuronet/dev_testnet_obscuroscan:latest
          registry-login-server: testnetobscuronet.azurecr.io
          registry-username: testnetobscuronet
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: dev-testnet-obscuroscan
          location: 'uksouth'
          restart-policy: 'Never'
          command-line: ./tools/obscuroscan/main/main --rpcServerAddress http://dev-testnet.obscu.ro:13000 --address 0.0.0.0:80
          ports: '80'
          cpu: 2
          memory: 2


